### ISSUE TITLE
Makefile crashes on macOS

### ISSUE THREAD

**Issue by mishaturnbull** [mishaturnbull/PySpeedTest#33]
Platform: macOS X 10.12 x64
VM Host: Windows 10.10.0.16299
(Yes, it's virtualized on Windows, but the Mac seems to have no idea about it)

Running the makefile (only sometimes) results in the following error:

```bash
FakeMac:PySpeedMonitor misha$ sudo make
python src/dependencies.py
Running emergency dependency download routine
+++ pyspeedtest present: True
+++ urllib3 present: True
+++ tkinter present: True
rm -rf dist
rm src/*.pyc; 
rm: src/*.pyc: No such file or directory
make: [preclean] Error 1 (ignored)
rm -rf __pycache__
pyinstaller -F -y --specpath build --clean --hidden-import urllib3 --hidden-import pyspeedtest --windowed -n PySpeedTest_v1.6.0_mac src/gui.py
133 INFO: PyInstaller: 3.3.1
134 INFO: Python: 2.7.10
153 INFO: Platform: Darwin-16.0.0-x86_64-i386-64bit
163 INFO: wrote build/PySpeedTest_v1.6.0_mac.spec
333 INFO: UPX is not available.
334 INFO: Removing temporary files and cleaning cache in /Users/misha/Library/Application Support/pyinstaller
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "/Library/Python/2.7/site-packages/PyInstaller-3.3.1-py2.7.egg/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Library/Python/2.7/site-packages/PyInstaller-3.3.1-py2.7.egg/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Library/Python/2.7/site-packages/PyInstaller-3.3.1-py2.7.egg/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Library/Python/2.7/site-packages/PyInstaller-3.3.1-py2.7.egg/PyInstaller/building/build_main.py", line 694, in build
    os.makedirs(pth)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 5] Input/output error: '/Volumes/VMware Shared Folders/PySpeedMonitor/dist'
make: *** [main] Error 1
```

The same errors happens running just `make`, without `sudo`.

**Comment by mishaturnbull** [comment]
Seems to be a problem with permission flags somewhere.

**Comment by mishaturnbull** [comment]
Appears to have been my own fault, using VMware shared folders seems buggy on OSx and Linux right now.  Closing -- `make` runs fine with/without `sudo` when pulled from GitHub into a different folder.
