### ISSUE TITLE
Auto-update does not detect new version

### ISSUE THREAD

**Issue by mishaturnbull** [mishaturnbull/PySpeedTest#40]
### What were you trying to do when the error occurred?
No error - lack of new version popup window.

### Did you get an error message?  If so, what did it say?
No.

### Are you able to reproduce the problem?  If so, how?
Yes, it happens every time.

### Platform details:

Operating system: Windows 10

Are you using the program:
  - One-file `.exe`

Is this the first time you've used (or attempted to use) the program? Yes.
  - If yes, is there a file called `config.ini` anywhere? Yes.
  
### Any other details that may be relevant:
Tested using version 2.0.0 (..1 behind the current release) so it has a new version to find.

**Comment by mishaturnbull** [comment]
Issue seems to be in the `is_version_greater` function in `__version__.py`.  Crashes if the version number supplied is not appended with a 'v':

```python
>>> is_version_greater("v2.0.1", "v2.0.0")
True
>>> is_version_greater("2.0.1", "2.0.0")
Traceback (most recent call last):
  File "C:\Users\Misha\PySpeedMonitor\src\__version__.py", line 25, in is_version_greater
    maj2, min2, pat2 = [int(i) for i in ver2[1:].split('-')[0].split('.')]
  File "C:\Users\Misha\PySpeedMonitor\src\__version__.py", line 25, in <listcomp>
    maj2, min2, pat2 = [int(i) for i in ver2[1:].split('-')[0].split('.')]
ValueError: invalid literal for int() with base 10: ''
```
